### ISSUE TITLE
NUnit Data Driven Results display incorrectly

### ISSUE THREAD

**Issue by jacobwiseman** [GHPReporter/Ghpr.NUnit#23] opened 2017-04-17 18:07 UTC
Using the new NUnit `TextFixtureSource `attribute **AND** feeding in complex objects as structured data-driven test input, the results as displayed in GHPReporter on the `run-test-list` page.   

Instead of displaying the real test namespace hierarchy, GHPReporter is using the namespace of the input objects as well.

![capture](https://cloud.githubusercontent.com/assets/27698749/25098435/89eb0a44-2376-11e7-8196-9756f17791fe.PNG)

**Comment by elv1s42** [comment] 2017-04-18 07:53
Hi @UltimateWombat 

I will try to reproduce this issue. 
But in general, test list is generated by splitting test's full name (where '.' is used as separator).
Probably it is just the NUnit creates full name for tests with `TextFixtureSource`

In any case, thank you for this issue, I will let you know about the results of my investigation.

**Comment by jacobwiseman** [comment] 2017-04-18 12:45
On the `TestHistory` tab, the test's Full Name is displayed as `Quality.Automation.Tests.ClientApiTests(3,System.Collections.Generic.Dictionary'2[System.String,System.String],Quality.Automation.QueryObjects.ClientApi.MyObject.MyPayload,Quality.Automation.QueryObjects.ClientApi.Models.MyOtherObject.MyOtherPayload,Quality.Automation.QueryObjects.Tools.Models.ThirdPayload).testFindOrCreateSomething`

Note that the majority of this Full Name is the input parameters.  The **actual** test Full Name is simply `Quality.Automation.Tests.ClientApiTests.testFindOrCreateSomething`.  So in reality, anything between the parentheses should be ignored.

**Comment by elv1s42** [comment] 2017-04-18 12:47
Hello again!

I think I found how to resolve this issue.
When you are using complex objects as structured data-driven test input NUnit generates Test full name by calling `.ToString()` method for your object. 
According to MSDN, the default implementation of the ToString method returns the fully qualified name of the type:
![2017-04-18 15_38_26- object tostring system](https://cloud.githubusercontent.com/assets/6689884/25131073/19b22776-244d-11e7-81f5-49212b9fe171.png)

I've created sample tests to reproduce this:
![2017-04-18 15_39_30-ghpr nunitexamples - microsoft visual studio](https://cloud.githubusercontent.com/assets/6689884/25131122/48768b10-244d-11e7-8a2a-09b4e3e0db63.png)
And as expected, I recieved wrong test list:
![2017-04-18 15_40_35-ghp report run page](https://cloud.githubusercontent.com/assets/6689884/25131265/bf264dc2-244d-11e7-83b0-50aa5ab924f7.png)
Here is full name of the test:
![2017-04-18 15_42_24-ghp report test page](https://cloud.githubusercontent.com/assets/6689884/25131276/c9c959b8-244d-11e7-94e0-f1fabc8b2fd2.png)

Then I've added new `.ToString()` method:
![2017-04-18 15_44_29-ghpr nunitexamples - microsoft visual studio](https://cloud.githubusercontent.com/assets/6689884/25131345/032ab710-244e-11e7-81eb-80eae1b37215.png)
And new test list looked much better:
![2017-04-18 15_45_42-ghp report run page](https://cloud.githubusercontent.com/assets/6689884/25131370/25d089ca-244e-11e7-80b9-96d2d198b4d2.png)
Because full name changed:
![2017-04-18 15_46_28-ghp report test page](https://cloud.githubusercontent.com/assets/6689884/25131402/45a98b84-244e-11e7-9c6e-1b05eb258215.png)

**Comment by elv1s42** [comment] 2017-04-18 12:49
So basically you can try to override 'ToString()' method for your complex objects.

**Comment by jacobwiseman** [comment] 2017-04-18 12:55
This works for custom objects, however if I am passing something like a Dictionary then the `System.Collections.Generic.Dictionary` namespace is passes.  I'd rather not have to extend the Dictionary class simply to overwrite the toString method.  

Could you perhaps ignore any of the namespace strings between the starting `(` and ending `)` that designates the input parameters?

**Comment by elv1s42** [comment] 2017-04-18 13:19
Yes, this is possible. Will do this with the next release for Ghpr.Core because this test list is generated by javascript controller.

**Comment by jacobwiseman** [comment] 2017-04-18 13:22
Excellent, thanks!

**Comment by elv1s42** [comment] 2017-04-18 16:24
Hello again!
I am afraid we have some issues with this fix.

1. First of all, if we ignore any of the namespace strings between the starting `(` and ending `)` for our case, we can brake another cases like this (and for several cases for Ghpr.SpecFlow.Plugin): 
![2017-04-18 19_19_04-ghpr nunitexamples - microsoft visual studio](https://cloud.githubusercontent.com/assets/6689884/25141328/ed0afb34-246b-11e7-9d3e-c170fdd8117f.png)
![2017-04-18 19_19_55-ghp report run page](https://cloud.githubusercontent.com/assets/6689884/25141379/11e547b6-246c-11e7-98ce-0e90864ba3f2.png)

2. Second one is related to test history. When our test is finished, we are creating Guid for our test. This Guid is created from test's full name, so we are expect this name to be unique. but for your case full name will not be unique.

So I think we need another approach for resolving this issue.

**Comment by jacobwiseman** [comment] 2017-04-18 18:03
1.  In the test.json file there are 2 fields in the json.   `name` and `fullName`.   It seems that if you could:
- filter out the namespace strings between the starting `(` and ending `)` from `fullname` for **organization & sorting** purposes on the run-test-list tab
- but still use the `name` field to display the test to the user.  

2.  I don't see how this is any different than the original problem.  If I was **only** sending in a complex object without a ToString() override before, then the `fullName` was already non-unique.

**Comment by elv1s42** [comment] 2017-04-18 18:09
1. Agree, this is what will be done.

2. I would suggest using override method to get unique test name.

**Comment by elv1s42** [comment] 2017-05-04 14:39
Hi, 
1. Fixed in new release.
2. I would suggest using override method to get unique test name:
http://stackoverflow.com/a/2024193/4185987

**Closed as completed** 2017-09-22 12:53 UTC
Labels: enhancement
